// Generated by Xata Codegen 0.26.6. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "blogPosts",
    columns: [
      { name: "title", type: "string" },
      { name: "publishDate", type: "datetime", defaultValue: "now" },
      { name: "description", type: "string" },
      { name: "postImage", type: "file" },
      { name: "altText", type: "string" },
      { name: "tags", type: "multiple" },
      { name: "content", type: "text" },
      { name: "slug", type: "string", unique: true },
    ],
    revLinks: [{ column: "blogPost", table: "comments" }],
  },
  {
    name: "works",
    columns: [
      { name: "name", type: "string" },
      { name: "sizeclass", type: "string" },
      { name: "type", type: "string" },
      { name: "image", type: "file" },
      { name: "altText", type: "string" },
      { name: "tags", type: "multiple" },
      { name: "order", type: "int" },
      { name: "content", type: "text" },
      { name: "siteLink", type: "string" },
      { name: "slug", type: "string" },
      { name: "screenshots", type: "file[]" },
    ],
  },
  {
    name: "comments",
    columns: [
      { name: "blogPost", type: "link", link: { table: "blogPosts" } },
      { name: "author", type: "string" },
      { name: "comment", type: "text" },
      { name: "replyToComment", type: "link", link: { table: "comments" } },
      { name: "isAdmin", type: "bool", notNull: true, defaultValue: "false" },
    ],
    revLinks: [{ column: "replyToComment", table: "comments" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type BlogPosts = InferredTypes["blogPosts"];
export type BlogPostsRecord = BlogPosts & XataRecord;

export type Works = InferredTypes["works"];
export type WorksRecord = Works & XataRecord;

export type Comments = InferredTypes["comments"];
export type CommentsRecord = Comments & XataRecord;

export type DatabaseSchema = {
  blogPosts: BlogPostsRecord;
  works: WorksRecord;
  comments: CommentsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Eetu-Rantanen-s-workspace-a3fodd.eu-central-1.xata.sh/db/portfolio-database",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
