// Generated by Xata Codegen 0.26.6. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "blogPosts",
    columns: [
      { name: "title", type: "string" },
      { name: "publishDate", type: "datetime", defaultValue: "now" },
      { name: "description", type: "string" },
      { name: "postImage", type: "file" },
      { name: "altText", type: "string" },
      { name: "tags", type: "multiple" },
      { name: "content", type: "text" },
      { name: "slug", type: "string", unique: true },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type BlogPosts = InferredTypes["blogPosts"];
export type BlogPostsRecord = BlogPosts & XataRecord;

export type DatabaseSchema = {
  blogPosts: BlogPostsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Eetu-Rantanen-s-workspace-a3fodd.eu-central-1.xata.sh/db/portfolio-database",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
