create table "public"."comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "author" text,
    "comment" text,
    "blogPost" text,
    "isAdmin" boolean default false,
    "replyToComment" bigint
);


alter table "public"."comments" enable row level security;

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."comments" add constraint "comments_blogPost_fkey" FOREIGN KEY ("blogPost") REFERENCES "blogPosts"(id) not valid;

alter table "public"."comments" validate constraint "comments_blogPost_fkey";

alter table "public"."comments" add constraint "comments_replyToComment_fkey" FOREIGN KEY ("replyToComment") REFERENCES comments(id) not valid;

alter table "public"."comments" validate constraint "comments_replyToComment_fkey";


